app_group:
  - read:
      path: /apps/system.eda.nokia.com
      method: GET

patch:
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: PATCH
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: PATCH
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}/_revs
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}/_revs
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}/_topology
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}/_topology
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: DELETE
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: DELETE
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.system.v1alpha1.monitor:
  - create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors
      method: POST
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: GET
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: PUT

com.nokia.eda.system.v1alpha1.monitor_aggregate_state:
  - create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates
      method: POST
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: GET
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: PUT

com.nokia.eda.system.v1alpha1.monitor_aggregate_state_list:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/monitoraggregatestates
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates
      method: GET
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates
      method: DELETE

com.nokia.eda.system.v1alpha1.monitor_aggregate_state_deleted_resources:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/_deleted
      method: GET

com.nokia.eda.system.v1alpha1.monitor_list:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/monitors
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors
      method: GET
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors
      method: DELETE

com.nokia.eda.system.v1alpha1.monitor_state:
  - create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates
      method: POST
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: GET
  - update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: PUT

com.nokia.eda.system.v1alpha1.monitor_state_list:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/monitorstates
      method: GET
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates
      method: GET
  - delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates
      method: DELETE

com.nokia.eda.system.v1alpha1.monitor_state_deleted_resources:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/_deleted
      method: GET

com.nokia.eda.system.v1alpha1.monitor_deleted_resources:
  - read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/_deleted
      method: GET

totalPaths: 21
totalSchemas: 43
usedSchemas: 16
unusedSchemas: 27
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoElemMetadata
  - TopoLinkEndpoint
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeState
  - TopoSchema
  - Topology
  - com.nokia.eda.system.v1alpha1.MonitorAggregateState_DeletedResourceEntry
  - com.nokia.eda.system.v1alpha1.MonitorAggregateState_metadata
  - com.nokia.eda.system.v1alpha1.MonitorState_DeletedResourceEntry
  - com.nokia.eda.system.v1alpha1.MonitorState_metadata
  - com.nokia.eda.system.v1alpha1.Monitor_DeletedResourceEntry
  - com.nokia.eda.system.v1alpha1.Monitor_metadata
