provider:
  name: system

data_sources:
  app_group:
    read:
      path: /apps/system.eda.nokia.com
      method: GET

  monitor:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: GET

  monitor_aggregate_state:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: GET

  monitor_aggregate_state_list:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates
      method: GET

  monitor_list:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors
      method: GET

  monitor_state:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: GET

  monitor_state_list:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates
      method: GET

  resource_list:
    read:
      path: /apps/system.eda.nokia.com/v1alpha1
      method: GET

resources:
  monitor:
    create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors
      method: POST
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: GET
    update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: PUT
    delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitors/{name}
      method: DELETE

  monitor_aggregate_state:
    create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates
      method: POST
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: GET
    update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: PUT
    delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitoraggregatestates/{name}
      method: DELETE

  monitor_state:
    create:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates
      method: POST
    read:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: GET
    update:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: PUT
    delete:
      path: /apps/system.eda.nokia.com/v1alpha1/namespaces/{namespace}/monitorstates/{name}
      method: DELETE
